#!/bin/bash

if [[ -z $BLOCK_INSTANCE ]]; then
    echo -n
    exit 0
fi
IFACE=$BLOCK_INSTANCE

STR=$(iw dev $IFACE link)
if [[  $STR == 'Not connected.' ]]; then
    echo " down"
    echo
    echo "#FF0000"
else
    ARR=(${STR// / })
    BSSID=${ARR[2]}
    SIGNAL=${ARR[20]}
    STR=$(iw dev $IFACE info)
    ARR=(${STR// / })
    SSID=${ARR[9]}
    CH=${ARR[15]}
    MHZ=${ARR[19]}

#    STR=$(ifconfig $IFACE)
#    ARR=(${STR// / })
#    IP=${ARR[5]}

    echo " $SSID ch:$CH [$MHZ MHz] ($SIGNAL dBm): $IP"
    echo
    echo "#FFFF99"
fi
