#!/bin/sh
if [ -z `mpop | grep 'new'` ]; then
exit
else
mkdir /tmp/attachments
uudeview -i ~/mail/inbox/new/* -p /tmp/attachments
ls /tmp/attachments
chmod 666 /tmp/attachments/*.torrent
mv /tmp/attachments/*.torrent /mnt/usb/torr/todo
rm /tmp/attachments/*
rm ~/mail/inbox/new/*
fi
