#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Windows 10" --class Windows --class os {
	savedefault
	insmod part_gpt
	insmod fat
	search --fs-uuid --no-floppy --set=root 82FD-E0C3 
	chainloader (${root})/EFI/Microsoft/Boot/bootmgfw.efi
}
